server:
  port: 8090

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:/data/simple
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

