spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${JDBCadress:192.168.99.100:5432/postgres}
    username: postgres
    password: postgres

server:
  port: ${STAFF_PORT:0}

eureka:
  instance:
    appname: complain_handling
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761/eureka/eureka/}
      