spring:
    main:
      banner-mode: off
    datasource:
      url: jdbc:h2:mem:mydb
      driver-class-name: org.h2.Driver
      username: test
      password: test
    h2:
      console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  security:
    user:
      password: ${eureka.password}
server:
  port: ${STAFF_PORT:8084}
management:
  server:
    port: ${server.port}
eureka:
  instance:
    appname: STAFF
    nonSecurePort: ${server.public-port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}:${server.public-port}/
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}

---
server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: prod
  h2:
    console.enabled: false
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${PUBLIC_PORT:80}
management:
  server:
    port: ${eureka.instance.nonSecurePort}
---
server:
  port: 80
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: docker
  h2:
    console.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  config:
    activate:
      on-profile: local
  h2:
    console.enabled: true
