version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "22:00"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "dependencies"
      - "CR_IGNORE"
      - "maven"
      - "bump"
    reviewers: 
      - "kostua16"
    target-branch: main
    # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:00"
    labels:
      - "dependabot"
      - "github-actions"
      - "bump"
      - "github"
    reviewers: 
      - "kostua16"

