
version: '3.4'

services:
  postgres:
    image: postgres:11.14
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080

  complains:
    build:
      context: .
      dockerfile: Complaints.Dockerfile
      args:
        BUILD_MOD: "complaint_handling_service"
    ports:
      - 8085:8085

volumes:
  pg_data:
