server:
  port: ${GUEST_PORT:57117}
spring:
  main:
    banner-mode: off
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
eureka:
  instance:
    appname: guest
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: prod
  h2:
    console.enabled: false
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${PUBLIC_PORT:80}
