server:
  port: ${GATEWAY_PORT:8765}
management:
  server:
    port: ${server.port}
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    user:
      password: ${eureka.password}
eureka:
  instance:
    appname: gateway
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: roomsApi
          uri: lb://complain_handling/rooms
          predicates:
            - PrefixPath=/api/rooms
        - id: complaintApi
          uri: lb://complain_handling/complaint
          predicates:
            - PrefixPath=/api/complaint
        - id: operationsApi
          uri: lb://guest/api/operations
          predicates:
            - PrefixPath=/api/operations
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${PUBLIC_PORT:80}
management:
  server:
    port: ${eureka.instance.nonSecurePort}
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: docker
