server:
  port: ${GATEWAY_PORT:8765}
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    user:
      password: ${eureka.password}
eureka:
  instance:
    appname: gateway
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: prod
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${PUBLIC_PORT:80}
