server:
  port: "${port:57116}"
spring:
  main:
    banner-mode: off
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    appname: bank
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${BANKSERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/eureka/}
