app:
  clients:
    logsApi: true

feign:
  httpclient:
    enabled: true
server:
  port: ${PORT:8085}
  public-port: ${PUBLIC_PORT:${server.port}}
management:
  server:
    port: ${server.public-port}
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console.enabled: true
  security:
    user:
      password: ${eureka.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
eureka:
  instance:
    appname: complain_handling
    nonSecurePort: ${server.public-port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.public-port}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}:${server.public-port}/
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
---
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://test:test@database:5432/test}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASS:}
  config:
    activate:
      on-profile: prod
  h2:
    console.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}

