server:
  port: ${PORT:8081}
  public-port: ${PUBLIC_PORT:${server.port}}
management:
  server:
    port: ${server.public-port}
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console.enabled: true
  security:
    user:
      password: ${eureka.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: localhost
    port: ${MAIL_PORT:1025}
    username: test
    password: test

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
eureka:
  instance:
    appname: GUEST
    nonSecurePort: ${server.public-port}
  password: ${USER_PASSWORD:password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/eureka/}
