# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Project

on:
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, edited, reopened, synchronize ]

jobs:
  Build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TKN }}
          fetch-depth: 0
      ###############
      # Install JDK #
      ###############
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      #########################
      # Check vulnerabilities #
      #########################
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif
      #######################
      # Upload scan results #
      #######################
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      #################
      # Build project #
      #################
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}  # Needed to get PR information, if any
        run: mvn -T 1 -B -e -ntp clean install pmd:pmd --file pom.xml -Dformat=net.sourceforge.pmd.renderers.SarifRenderer
      #######################################
      # Add 'build_failed' label if build failed #
      #######################################
      - name: Failure actions
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          github-token: ${{secrets.GH_TKN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/if_build_fails.js`)
            await script({github, context})
      ##############################################
      # Add 'build_passed' label if build success  #
      ##############################################
      - name: Success actions
        uses: actions/github-script@v6
        if: ${{ success() }}
        with:
          github-token: ${{secrets.GH_TKN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/if_build_success.js`)
            await script({github, context})

  Validate_commit_message:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4.1.11
        with:
          helpUrl: https://github.com/kostua16/TLT_NC_AMA_2021/blob/main/CONTRIBUTING.MD
          configFile: .github/commitlint.config.js
          firstParent: true
