name: docs

on:
  push:
    branches: [ master, main ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          cp -rf target/site/apidocs/. docs

      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: docs

      - name: Log javadoc-cleanup output
        run: |
          echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

      - name: Commit documentation changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Spec163'
            git config --global user.email 'super_spec163@mail.ru'
            git add -A
            git commit -m "Automated API website updates."
            git push -u origin master
          fi
