# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Add PR banner

on:
  pull_request:
    types: [opened]

jobs:
  Build:
    name: Add banner to pull request
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TKN }}
          fetch-depth: 0
      ##############
      # Add banner #
      ##############
      - uses: zattoo/output@v2
        name: Add banner
        with:
          token:  ${{ secrets.GH_TKN }}
          sources: '.github/docs/pr.md'
